x-database-variables: &database-variables
  POSTGRES_DB: ${POSTGRES_DB:-sourcetool_development}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

x-go-variables: &go-variables
  GOMODCACHE: /gomodcache

services:
  backend:
    image: golang:1.24
    command: bash -c "
      go run ./devtools/cmd/db/main.go migrate &&
      go run ./cmd/onprem-portal"
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    environment:
      <<: [*database-variables, *go-variables]
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/trysourcetool/onprem-portal
      - gomodcache:/gomodcache
    working_dir: /go/src/github.com/trysourcetool/onprem-portal

  nginx:
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  postgres:
    image: postgres:15
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      <<: *database-variables
    volumes:
      - pgdata:/var/lib/postgresql/data:cached

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass password

volumes:
  pgdata:
  gomodcache:
