/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as layoutDefaultImport } from './routes/layout-default'
import { Route as indexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as BillingIndexImport } from './routes/billing/index'
import { Route as SignupFollowupIndexImport } from './routes/signup/followup/index'
import { Route as LoginEmailSentIndexImport } from './routes/login/emailSent/index'
import { Route as AuthMagicAuthenticateIndexImport } from './routes/auth/magic/authenticate/index'
import { Route as AuthGoogleCallbackIndexImport } from './routes/auth/google/callback/index'

// Create/Update Routes

const layoutDefaultRoute = layoutDefaultImport.update({
  id: '/_default',
  getParentRoute: () => rootRoute,
} as any)

const indexRoute = indexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

const BillingIndexRoute = BillingIndexImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

const SignupFollowupIndexRoute = SignupFollowupIndexImport.update({
  id: '/signup/followup/',
  path: '/signup/followup/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

const LoginEmailSentIndexRoute = LoginEmailSentIndexImport.update({
  id: '/login/emailSent/',
  path: '/login/emailSent/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

const AuthMagicAuthenticateIndexRoute = AuthMagicAuthenticateIndexImport.update(
  {
    id: '/auth/magic/authenticate/',
    path: '/auth/magic/authenticate/',
    getParentRoute: () => layoutDefaultRoute,
  } as any,
)

const AuthGoogleCallbackIndexRoute = AuthGoogleCallbackIndexImport.update({
  id: '/auth/google/callback/',
  path: '/auth/google/callback/',
  getParentRoute: () => layoutDefaultRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutDefaultImport
      parentRoute: typeof rootRoute
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/billing/': {
      id: '/_default/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingIndexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/login/': {
      id: '/_default/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/login/emailSent/': {
      id: '/_default/login/emailSent/'
      path: '/login/emailSent'
      fullPath: '/login/emailSent'
      preLoaderRoute: typeof LoginEmailSentIndexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/signup/followup/': {
      id: '/_default/signup/followup/'
      path: '/signup/followup'
      fullPath: '/signup/followup'
      preLoaderRoute: typeof SignupFollowupIndexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/auth/google/callback/': {
      id: '/_default/auth/google/callback/'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackIndexImport
      parentRoute: typeof layoutDefaultImport
    }
    '/_default/auth/magic/authenticate/': {
      id: '/_default/auth/magic/authenticate/'
      path: '/auth/magic/authenticate'
      fullPath: '/auth/magic/authenticate'
      preLoaderRoute: typeof AuthMagicAuthenticateIndexImport
      parentRoute: typeof layoutDefaultImport
    }
  }
}

// Create and export the route tree

interface layoutDefaultRouteChildren {
  indexRoute: typeof indexRoute
  BillingIndexRoute: typeof BillingIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginEmailSentIndexRoute: typeof LoginEmailSentIndexRoute
  SignupFollowupIndexRoute: typeof SignupFollowupIndexRoute
  AuthGoogleCallbackIndexRoute: typeof AuthGoogleCallbackIndexRoute
  AuthMagicAuthenticateIndexRoute: typeof AuthMagicAuthenticateIndexRoute
}

const layoutDefaultRouteChildren: layoutDefaultRouteChildren = {
  indexRoute: indexRoute,
  BillingIndexRoute: BillingIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginEmailSentIndexRoute: LoginEmailSentIndexRoute,
  SignupFollowupIndexRoute: SignupFollowupIndexRoute,
  AuthGoogleCallbackIndexRoute: AuthGoogleCallbackIndexRoute,
  AuthMagicAuthenticateIndexRoute: AuthMagicAuthenticateIndexRoute,
}

const layoutDefaultRouteWithChildren = layoutDefaultRoute._addFileChildren(
  layoutDefaultRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof layoutDefaultRouteWithChildren
  '/': typeof indexRoute
  '/billing': typeof BillingIndexRoute
  '/login': typeof LoginIndexRoute
  '/login/emailSent': typeof LoginEmailSentIndexRoute
  '/signup/followup': typeof SignupFollowupIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackIndexRoute
  '/auth/magic/authenticate': typeof AuthMagicAuthenticateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/billing': typeof BillingIndexRoute
  '/login': typeof LoginIndexRoute
  '/login/emailSent': typeof LoginEmailSentIndexRoute
  '/signup/followup': typeof SignupFollowupIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackIndexRoute
  '/auth/magic/authenticate': typeof AuthMagicAuthenticateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_default': typeof layoutDefaultRouteWithChildren
  '/_default/': typeof indexRoute
  '/_default/billing/': typeof BillingIndexRoute
  '/_default/login/': typeof LoginIndexRoute
  '/_default/login/emailSent/': typeof LoginEmailSentIndexRoute
  '/_default/signup/followup/': typeof SignupFollowupIndexRoute
  '/_default/auth/google/callback/': typeof AuthGoogleCallbackIndexRoute
  '/_default/auth/magic/authenticate/': typeof AuthMagicAuthenticateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/billing'
    | '/login'
    | '/login/emailSent'
    | '/signup/followup'
    | '/auth/google/callback'
    | '/auth/magic/authenticate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/login'
    | '/login/emailSent'
    | '/signup/followup'
    | '/auth/google/callback'
    | '/auth/magic/authenticate'
  id:
    | '__root__'
    | '/_default'
    | '/_default/'
    | '/_default/billing/'
    | '/_default/login/'
    | '/_default/login/emailSent/'
    | '/_default/signup/followup/'
    | '/_default/auth/google/callback/'
    | '/_default/auth/magic/authenticate/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  layoutDefaultRoute: typeof layoutDefaultRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  layoutDefaultRoute: layoutDefaultRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "root.tsx",
      "children": [
        "/_default"
      ]
    },
    "/_default": {
      "filePath": "layout-default.tsx",
      "children": [
        "/_default/",
        "/_default/billing/",
        "/_default/login/",
        "/_default/login/emailSent/",
        "/_default/signup/followup/",
        "/_default/auth/google/callback/",
        "/_default/auth/magic/authenticate/"
      ]
    },
    "/_default/": {
      "filePath": "index.tsx",
      "parent": "/_default"
    },
    "/_default/billing/": {
      "filePath": "billing/index.tsx",
      "parent": "/_default"
    },
    "/_default/login/": {
      "filePath": "login/index.tsx",
      "parent": "/_default"
    },
    "/_default/login/emailSent/": {
      "filePath": "login/emailSent/index.tsx",
      "parent": "/_default"
    },
    "/_default/signup/followup/": {
      "filePath": "signup/followup/index.tsx",
      "parent": "/_default"
    },
    "/_default/auth/google/callback/": {
      "filePath": "auth/google/callback/index.tsx",
      "parent": "/_default"
    },
    "/_default/auth/magic/authenticate/": {
      "filePath": "auth/magic/authenticate/index.tsx",
      "parent": "/_default"
    }
  }
}
ROUTE_MANIFEST_END */
